name: Build and Deploy Preview to Netlify

# This workflow builds the frontend and deploys it as a preview to Netlify
# Triggers: Pull requests with frontend changes, and manual workflow dispatch
# Site ID: 234d39c1-554b-4590-80e5-099cfcb6ddae
# Requires: NETLIFY_AUTH_TOKEN secret

on:
  pull_request:
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy Preview to Netlify
        uses: netlify/actions/cli@v4
        with:
          args: deploy --dir=dist --site 234d39c1-554b-4590-80e5-099cfcb6ddae --json
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
